<?xml version="1.0" encoding="utf-8"?>
<Database Name="Northwind" Class="NorthwindDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SSCI-STK-05\SQLEXPRESS;Initial Catalog=Northwind;Integrated Security=True" SettingsObjectName="LINQChapter13.Properties.Settings" SettingsPropertyName="NorthwindConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustomerID" Type="System.String" DbType="NChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="ContactName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ContactTitle" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Association Name="Customer_Order" Member="Orders" OtherKey="CustomerID" Type="Order" />
    </Type>
    <InsertFunction FunctionId="FunctionId1">
      <Argument Parameter="customerID" Member="CustomerID" />
      <Argument Parameter="companyName" Member="CompanyName" />
      <Argument Parameter="contactName" Member="ContactName" />
      <Argument Parameter="contactTitle" Member="ContactTitle" />
      <Argument Parameter="address" Member="Address" />
      <Argument Parameter="city" Member="City" />
      <Argument Parameter="region" Member="Region" />
      <Argument Parameter="postalCode" Member="PostalCode" />
      <Argument Parameter="country" Member="Country" />
      <Argument Parameter="phone" Member="Phone" />
      <Argument Parameter="fax" Member="Fax" />
    </InsertFunction>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="OrderID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.String" DbType="NChar(5)" CanBeNull="true" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrderDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RequiredDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ShippedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ShipVia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Freight" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ShipName" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="ShipAddress" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="ShipCity" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="ShipRegion" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="ShipPostalCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ShipCountry" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Association Name="Customer_Order" Member="Customer" ThisKey="CustomerID" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Id="FunctionId1" Name="dbo.InsertCustomer" Method="InsertCustomer">
    <Parameter Name="CustomerID" Parameter="customerID" Type="System.String" DbType="NChar(5)" />
    <Parameter Name="CompanyName" Parameter="companyName" Type="System.String" DbType="NVarChar(40)" />
    <Parameter Name="ContactName" Parameter="contactName" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="ContactTitle" Parameter="contactTitle" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="NVarChar(60)" />
    <Parameter Name="City" Parameter="city" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="Region" Parameter="region" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="PostalCode" Parameter="postalCode" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Country" Parameter="country" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="NVarChar(24)" />
    <Parameter Name="Fax" Parameter="fax" Type="System.String" DbType="NVarChar(24)" />
    <Return Type="System.Int32" />
  </Function>
</Database>